spring.application.name=Quora
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/Quora
spring.datasource.username=springstudent
spring.datasource.password=springstudent
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

